### ISSUE TITLE
can you make this repo to a release version?

### ISSUE THREAD

**Issue by mindcont** [zimenglan-sysu-512/pose_action_caffe#1]
你好，我对你的这个工作很感兴趣，观察到你做了大量的工作，请问你有时间的话可以把代码从你的环境中分割出来吗？一个基础版本、满足一个简单的网络训练，测试即可，非常感谢

**Comment by zimenglan-sysu-512** [comment]
Sorry about that, so long to reply u.

I don't have a plan to simply this repo. you can select what you want.

**Comment by mindcont** [comment]
Thanks and Cheers ~🍻
